# Generated by Django 2.1.7 on 2019-03-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='detaiil',
            new_name='detail',
        ),
    ]
